const PDFDocument = require('pdfkit');

/**
 * Generates a PDF report and streams it directly to the Express response.
 * @param {Object} patient - The patient data object (from MongoDB or the request body)
 * @param {Object} res - The Express response object
 */
const generatePatientReport = (patient, res) => {
    // 1. Initialize the PDF document
    const doc = new PDFDocument({ margin: 50 });

    // 2. Set the response headers so the browser knows to download a PDF
    res.setHeader('Content-disposition', `attachment; filename=HemoScan_Report_${patient.name.replace(/\s+/g, '_')}.pdf`);
    res.setHeader('Content-type', 'application/pdf');

    // 3. Pipe the PDF directly to the Express response stream
    doc.pipe(res);

    // --- HEADER ---
    doc.font('Helvetica-Bold').fontSize(24).text('HemoScan AI', { align: 'center' });
    doc.font('Helvetica').fontSize(12).text('Automated Anemia Detection & Risk Analysis', { align: 'center' });
    doc.moveDown(2);

    // --- PATIENT DEMOGRAPHICS ---
    doc.font('Helvetica-Bold').fontSize(14).text('Patient Information');
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke(); // Draw a line
    doc.moveDown(0.5);

    doc.font('Helvetica').fontSize(12);
    doc.text(`Name: ${patient.name}`);
    doc.text(`Age/Gender: ${patient.age} / ${patient.gender}`);
    doc.text(`Mobile No: ${patient.mob_no}`);
    doc.text(`Date of Report: ${new Date().toLocaleDateString()}`);
    doc.moveDown(2);

    // --- HEMATOLOGY DATA (The Blood Numbers) ---
    doc.font('Helvetica-Bold').fontSize(14).text('Hematology Parameters (CBC)');
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);

    doc.font('Helvetica').fontSize(12);
    // Formatting the vitals in two columns for a professional look
    const startY = doc.y;
    doc.text(`Hemoglobin (Hb): ${patient.hb} g/dL`, 50, startY);
    doc.text(`PCV: ${patient.pcv} %`, 300, startY);
    doc.text(`MCH: ${patient.mch} pg`, 50, startY + 20);
    doc.text(`RBC: ${patient.rbc} mill/cu.mm`, 300, startY + 20);
    doc.text(`MCV: ${patient.mcv} fL`, 50, startY + 40);
    doc.text(`MCHC: ${patient.mchc} g/dL`, 300, startY + 40);
    
    doc.moveDown(4); // Move down past the columns

    // --- AI DIAGNOSIS ---
    // Reset X margin after columns
    doc.x = 50; 
    doc.font('Helvetica-Bold').fontSize(14).text('AI Diagnostic Analysis');
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);

    // Color-code the result (Red for Anemic, Green for Normal)
    const diagnosisColor = patient.ai_diagnosis === 'Anemic' ? 'red' : 'green';
    
    doc.font('Helvetica-Bold').fontSize(16).fillColor(diagnosisColor).text(`Status: ${patient.ai_diagnosis}`);
    doc.font('Helvetica').fontSize(12).fillColor('black').text(`AI Confidence Score: ${patient.confidence_score}%`);
    doc.moveDown(2);


    doc.font('Helvetica-Oblique').fontSize(10).fillColor('gray');
    doc.text('Disclaimer: This report is generated by HemoScan AI as a clinical assistant tool. It is not a substitute for professional medical advice, diagnosis, or treatment.', {
        align: 'center',
        width: 500
    });

    // 4. Finalize the PDF file 
    doc.end();
};

const patientReport=generatePatientReport;
module.exports=patientReport;
